title: Gopu's Gains
author: rgopu123
email: largestpizza@gmail.com
theme: minima
description: > # this means to ignore newlines until "baseurl:"
  I am Mr. Gopu and I love big brolic men!

# social links
twitter_username: pizza # DO NOT include the @ character, or else the build will fail!
github_username:  warrior # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
